- name: Compose Image Builder Instance
  gather_facts: yes
  hosts: localhost
  vars_files:
    - vars/config.yaml
  tasks:
    - name: Initiate Compose
      ansible.builtin.include_role:
        name: hosted-image-builder
      vars:
        action: compose

    - name: Wait for Compose to Complete
      ansible.builtin.include_role:
        name: hosted-image-builder
      vars:
        action: wait
        compose_id: "{{ compose_results.json.id }}"

    - name: Download Image
      ansible.builtin.include_role:
        name: hosted-image-builder
      vars:
        action: download
        compose_id: "{{ compose_results.json.id }}"
