- name: Configure Quay
  ansible.builtin.include_tasks:
    file: quay.yaml

- name: Enable Cockpit/Composer/Apache
  ansible.builtin.systemd:
    state: started
    enabled: yes
    name: "{{ item }}"
  loop:
    - osbuild-composer.socket
    - cockpit.socket
    - httpd.service

- name: Set Root Password
  ansible.builtin.user:
    name: root
    password: "{{ hib_root_password | password_hash('sha512') }}"
    update_password: always
  when:
    - platform == "aws"
