- name: Configure Quay
  ansible.builtin.include_tasks:
    file: quay.yaml

- name: Install Packages
  ansible.builtin.dnf:
    state: latest
    name:
      - osbuild-composer
      - composer-cli
      - cockpit-composer
      - bash-completion
      - genisoimage
      - httpd
      - syslinux
    update_cache: yes

- name: Enable Cockpit/Composer/Apache
  ansible.builtin.systemd:
    state: started
    enabled: yes
    name: "{{ item }}"
  loop:
    - osbuild-composer.socket
    - cockpit.socket
    - httpd.service
