- name: Configure Quay
  ansible.builtin.include_tasks:
    file: quay.yaml

- name: Install Packages
  ansible.builtin.dnf:
    state: latest
    name:
      - osbuild-composer
      - composer-cli
      - cockpit-composer
      - bash-completion
      - firewalld
      - genisoimage
      - httpd
      - syslinux
    update_cache: yes

- name: Enable Cockpit/Composer/Firewalld/Apache
  ansible.builtin.systemd:
    state: started
    enabled: yes
    name: "{{ item }}"
  loop:
    - osbuild-composer.socket
    - cockpit.socket
    - httpd.service
    - firewalld

- name: Enable Firewall Ports for Cockpit/Composer/Apache
  ansible.posix.firewalld:
    permanent: yes
    immediate: yes
    service: "{{ item }}"
    state: enabled
  loop:
    - cockpit
    - http
    - https
