- name: Copy Disk Image
  ansible.builtin.copy:
    dest: "{{ hib_libvirt_disk_path }}/{{ hib_name }}.qcow2"
    group: root
    mode: u+rw,g-wx,o-rwx
    owner: root
    src: "/tmp/{{ hib_name }}.qcow2"
  tags:
    - setup

- name: Set Root Password
  ansible.builtin.command:
    argv:
      - "virt-customize"
      - "-a"
      - "{{ hib_libvirt_disk_path }}/{{ hib_name }}.qcow2"
      - "--root-password"
      - "password:{{ hib_root_password }}"
  tags:
    - setup

- name: Generate MAC Address
  ansible.builtin.shell:
    cmd: |
      echo -n {{ hib_name | quote }} | md5sum | sed 's/\(..\)/\1:/g' | cut -b1-8
  register: mac_address_results

- name: Create Image Builder VM
  community.libvirt.virt:
    autostart: yes
    command: define
    xml: "{{ lookup('template', 'libvirt-vm.xml.j2') }}"

- name: Start Image Builder VM
  community.libvirt.virt:
    name: "{{ hib_name }}"
    state: running
