# For some reason resizing via HIB doesn't work!?
- name: Create Larger qcow2 Disk
  ansible.builtin.command:
    argv:
      - "qemu-img"
      - "create"
      - "-f"
      - "qcow2"
      - "-o"
      - "preallocation=metadata"
      - "{{ hib_libvirt_disk_path | quote }}/{{ hib_name | quote }}.qcow2"
      - "{{ hib_root_filesystem_size }}G"
  tags:
    - setup

- name: Resize/Expand
  ansible.builtin.command:
    argv:
      - "virt-resize"
      - "--expand"
      - "/dev/sda4"
      - "/tmp/{{ hib_name | quote }}.qcow2"
      - "{{ hib_libvirt_disk_path | quote }}/{{ hib_name | quote }}.qcow2"
  tags:
    - setup

- name: Configure Image
  ansible.builtin.command:
    argv:
      - "virt-customize"
      - "-a"
      - "{{ hib_libvirt_disk_path | quote }}/{{ hib_name | quote }}.qcow2"
      - "--uninstall"
      - "cloud-init"
      - "--selinux-relabel"
      - "--ssh-inject"
      - "root:file:{{ hib_libvirt_ssh_public_key_path | quote }}"
      - "--root-password"
      - "password:{{ hib_root_password }}"
  tags:
    - setup

- name: Generate MAC Address
  ansible.builtin.shell:
    cmd: |
      echo -n {{ hib_name | quote }} | md5sum | sed 's/\(..\)/\1:/g' | cut -b1-8
  register: mac_address_results

- name: Create Image Builder VM
  community.libvirt.virt:
    autostart: yes
    command: define
    xml: "{{ lookup('template', 'libvirt-vm.xml.j2') }}"

- name: Start Image Builder VM
  community.libvirt.virt:
    name: "{{ hib_name }}"
    state: running
