- name: Assert Variables are Defined
  ansible.builtin.assert:
    that:
      - platform is defined

- name: Inventory using KVM
  ansible.builtin.include_tasks:
    file: libvirt.yaml
  when:
    - platform == "libvirt"

- name: Inventory using AWS
  ansible.builtin.include_tasks:
    file: aws.yaml
  when:
    - platform == "aws"

- name: Wait for Host
  ansible.builtin.wait_for:
    host: "{{ hostvars[hib_name].ansible_ssh_host }}"
    port: 22
  when:
    - imi_wait_for_host is defined
