- name: Assert Variables are Defined
  ansible.builtin.assert:
    that:
      - platform is defined

- name: Destroy using KVM
  ansible.builtin.include_tasks:
    file: libvirt.yaml
  when:
    - platform == "libvirt"

- name: Destroy using AWS
  ansible.builtin.include_tasks:
    file: aws.yaml
  when:
    - platform == "aws"
